# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d53f44d6892b96bfe321726eafdc12119fcb3c794dd07fbc458a496323e91a97c3d069ade12886e53879dce9de085ae2972753d531953b03de63d2c0c4a22745

test:
  secret_key_base: ca235f8124fdf2b5fe6ca9cf38ded0b41268eda5295fee2edff8565be65d795bdaceec533862a155f52abf712be9f0eeccad2fe2dd80f5a88bf5f7df2eb16b52

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
